# GitHub Pages Configuration for DIYOMX
title: ديومكس - تطبيقات ذكية وإنجازات رقمية
description: موقع ديومكس الرسمي - فريق متخصص في تطوير التطبيقات الذكية والحلول الرقمية المبتكرة
author: فريق ديومكس
email: diyomx@gmail.com
baseurl: ""
url: "https://diyomx.com"

# Site settings
lang: ar
direction: rtl
timezone: Asia/Riyadh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# GitHub Pages specific settings
github: [metadata]
safe: true
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .gitignore
  - .DS_Store
  - Thumbs.db
  - *.log
  - .vscode/
  - .idea/
  - .tmp/
  - .cache/
  - .sass-cache/
  - .env*
  - *.bak
  - *.backup
  - *.old
  - test/
  - tests/
  - spec/
  - __tests__/
  - docs/
  - documentation/

# Include in processing
# include:
#   - _pages

# Collections
# collections:
#   apps:
#     output: true
#     permalink: /:collection/:name/

# Defaults
# defaults:
#   - scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "default"

# Social media links
social:
  twitter: diyomx
  instagram: diyomx
  youtube: diyomx

# Navigation
navigation:
  - title: الرئيسية
    url: /
  - title: من نحن
    url: /about.html
  - title: اتصل بنا
    url: /contact.html

# SEO
seo:
  type: Organization
  name: ديومكس
  description: فريق متخصص في تطوير التطبيقات الذكية والحلول الرقمية المبتكرة
  url: https://diyomx.com
  logo: /assets/images/logo.png
  sameAs:
    - https://twitter.com/diyomx
    - https://instagram.com/diyomx
